---
- name: Install Docker and initialize Docker Swarm
  hosts: all
  become: yes

  vars:
    ssh_key_path_default_user: ~/.ssh/nome_da_chave.pub
    ssh_path_private_key: ~/.ssh/nome_da_chave
    

  tasks:
    - name: Add the user 'ansible' and add it to 'sudo'
      user:
        name: ansible
        group: sudo 

    - name: Add SSH key to 'ansible'
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', ssh_key_path_default_user) }}" 

    - name: Wait for apt to unlock
      become: yes
      shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;  

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Initialize Docker Swarm (on manager only)
      shell: |
        docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
        docker swarm join-token worker -q > /tmp/swarm_worker_token
      when: is_manager

    - name: Get Swarm join token (on manager)
      command: cat /tmp/swarm_worker_token
      register: worker_token
      when: is_manager

    - name: Join Docker Swarm (on workers only)
      shell: "docker swarm join --token {{ hostvars[groups['managers'][0]].worker_token.stdout }} {{ hostvars[groups['managers'][0]].ansible_default_ipv4.address }}:2377"
      when: not is_manager

    # Configuração do Nginx e Deploy do HTML no Docker Swarm
    - name: Create a directory for Dockerfile and HTML
      file:
        path: /home/ansible/docker/nginx
        state: directory
        owner: ansible
        group: ansible
        mode: 0755

    - name: Create a Dockerfile for Nginx
      copy:
        dest: /home/ansible/docker/nginx/Dockerfile
        content: |
          FROM nginx:latest
          COPY index.html /usr/share/nginx/html/index.html

    - name: Create a simple HTML file
      copy:
        dest: /home/ansible/docker/nginx/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hello World</title>
          </head>
          <body>
              <h1>Hello from Nginx container!</h1>
          </body>
          </html>

    - name: Build Nginx Docker image
      command: docker build -t mynginx /home/ansible/docker/nginx/

    - name: Deploy Nginx service in Docker Swarm
      shell: |
        docker service create --name nginx_service --publish 80:80 mynginx
      when: is_manager

