---
- name: "Instalar pacotes necessários"
  ansible.builtin.apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: 'present'
    update_cache: true

- name: "Baixar chave GPG do Docker"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg

- name: "Adicionar chave GPG ao apt"
  ansible.builtin.apt_key:
    file: /tmp/docker.gpg
    state: 'present'

- name: "Adicionar repositório Docker"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb['codename'] }} stable"
    state: 'present'

- name: "Instalar Docker"
  ansible.builtin.apt:
    name: docker-ce
    state: 'present'

- name: "Iniciar e habilitar Docker"
  ansible.builtin.service:
    name: docker
    state: 'started'
    enabled: true
