---
- name: Instalar pacotes necessários
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Adicionar a chave GPG do Docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Adicionar repositório Docker
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Instalar Docker
  apt:
    name: docker-ce
    state: present

- name: Iniciar e habilitar Docker
  service:
    name: docker
    state: started
    enabled: yes