name: fast-cd

on:
  workflow_dispatch:  # Permite executar o deploy manualmente pelo GitHub Actions
  push:
    tags:
      - 'v*.*.*'  # Executa o workflow quando uma tag de versão for criada (ex: v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
  

      - name: Listar arquivos do diretório Terraform
        run: ls -la ./terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
                 
      - name: Terraform Init
        run: 
          terraform init 
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS}}
      
       
      - name: Terraform Apply
        run:  |
          cd ./terraform
          terraform  apply  -auto-approve  -input=false 
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS}}

      - name: Setup SSH for Ansible
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        run: ansible-playbook -i playbooks/inventory playbooks/install_docker.yml
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS}}

        
      
