name: fast-cd
on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*.*.*'  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      

      - name: Configurar credenciais Google
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
           echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > /tmp/google-credentials.json
           chmod 400 /tmp/google-credentials.json
           export GOOGLE_APPLICATION_CREDENTIALS="/tmp/google-credentials.json"
          
              
      - name: Terraform Init com Reconfigure
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/google-credentials.json
        run: terraform -chdir=./terraform init -reconfigure
       
      - name: Terraform Apply
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/google-credentials.json
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform -chdir=./terraform apply -auto-approve

      - name: Set up SSH for Ansible
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/google-credentials.json
        run: ansible-playbook -i playbooks/inventory playbooks/install_docker.yml