name: fast-cd

on:
  workflow_dispatch:  # Permite executar o deploy manualmente pelo GitHub Actions
  push:
    tags:
      - 'v*.*.*'  # Executa o workflow quando uma tag de versão for criada (ex: v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Listar arquivos do diretório Terraform
        run: ls -la ./terraform

      - name: Criando arquivo de credencial
        run: echo "$GOOGLE_CREDENTIAL" > ./credential.json

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init com Reconfigure
        run: terraform -chdir=./terraform init -reconfigure
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./credential.json

      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve

      - name: Set up SSH for Ansible
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.yml playbook.yml

